name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Adjust this to match your project's requirements

      - name: Change directory and install dependencies with retry
        run: |
          cd client/gabSpot
          n=0
          until [ "$n" -ge 5 ]
          do
            npm install && break  # Attempts to install dependencies
            n=$((n+1))  # Increment the counter
            sleep 15  # Wait for 15 seconds before retrying
          done

      - name: Build the project
        run: |
          cd client/gabSpot
          npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIREBASE_DEPLOY_GABSPOT }}
          channelId: live
          projectId: firebase-deploy-gabspot
          entryPoint: client/gabSpot  # Pointing to the directory where firebase.json is located
