name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Change directory and install dependencies
        run: |
          cd client/gabSpot
          npm install  # Installs all dependencies including Vite

      - name: Build the project
        run: |
          cd client/gabSpot
          npm run build  # Runs the build script which uses Vite

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIREBASE_DEPLOY_GABSPOT }}
          channelId: live
          projectId: firebase-deploy-gabspot
